### ISSUE TITLE
Glitches of new release

### ISSUE THREAD

**Issue by Titan-C** [honmaple/org-python#2]
Thank you for taking care of the syntax highlighting issue.
I tested the new release and stumbled upon other problems
Example
```python
source  = '* Hello World\n** People First\n*** Their cultural differences'
to_html(source, toc=True)
```
- Here the first word of all headings becomes of todo class
- There is no space between the first and second word of every heading
- The first word of every heading disappears on the table of contents
- The Table of contents is a flat list instead of nested as before

**Comment by honmaple** [comment]
https://github.com/honmaple/org-python/commit/9037d9801316f15873fa355f91ad90c6b6682ebe

Please check the commit.

**Comment by Titan-C** [comment]
Yes the latest release works for me. Thank you
